version: '3.9'

services:
  bot:
    build: .
    container_name: currency_bot
    env_file:
      - .env
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - EXCHANGE_RATE_API_KEY=${EXCHANGE_RATE_API_KEY}
    restart: unless-stopped